export const DataUser = [
    {
        id: 1,
        name: "Costumer",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Costumer",
    },
    {
        id: 2,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Costumer",
    },
    {
        id: 3,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Costumer",
    },
    {
        id: 4,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Costumer",
    },
    {
        id: 5,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Costumer",
    },
    {
        id: 6,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Costumer",
    },
    {
        id: 7,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Costumer",
    },
    {
        id: 8,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Costumer",
    },
    {
        id: 9,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Costumer",
    },
    {
        id: 10,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Costumer",
    },
    {
        id: 11,
        name: "Costumer",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Author",
    },
    {
        id: 12,
        name: "Costumer",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Author",
    },
    {
        id: 13,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-50 bg-gray-100 hover:bg-gray-50",
        role: "Author",
    },
    {
        id: 14,
        name: "Costumer",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Author",
    },
    {
        id: 15,
        name: "Costumer",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Author",
    },
    {
        id: 16,
        name: "Costumer",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Author",
    },
    {
        id: 17,
        name: "Costumer",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Author",
    },
    {
        id: 18,
        name: "Author",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Super Admin",
    },
    {
        id: 19,
        name: "Author",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Super Admin",
    },
    {
        id: 20,
        name: "Author",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Super Admin",
    },
    {
        id: 21,
        name: "Author",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Super Admin",
    },
    {
        id: 22,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Super Admin",
    },
    {
        id: 23,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "BDE",
    },
    {
        id: 24,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "BDE",
    },
    {
        id: 25,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "BDE",
    },
    {
        id: 26,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "BDE",
    },
    {
        id: 27,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Advisor",
    },
    {
        id: 28,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Advisor",
    },
    {
        id: 29,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Advisor",
    },
    {
        id: 30,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Advisor",
    },
    {
        id: 31,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        role: "Admin Office",
    },
    {
        id: 32,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Admin Office",
    },
    {
        id: 33,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Admin Office",
    },
    {
        id: 34,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Admin Office",
    },
    {
        id: 35,
        name: "User",
        phone: "081211367526",
        email: "jhondoe@example.com",
        color: "border-b border-gray-200 hover:bg-gray-100",
        role: "Admin Office",
    },
];

export const DataTabList = [
    {
        id: 1,
        name: "Costumer",
        role: "Costumer",
    },
    {
        id: 2,
        name: "Author",
        role: "Author",
    },
    {
        id: 3,
        name: "Super Admin",
        role: "Super Admin",
    },
    {
        id: 4,
        name: "BDE",
        role: "BDE",
    },
    {
        id: 5,
        name: "Advisor",
        role: "Advisor",
    },
    {
        id: 6,
        name: "Admin Office",
        role: "Admin Office",
    },
];

export const DataTabListNews = [
    {
        id: 1,
        name: "News List",
        for: "News",
    },
    {
        id: 2,
        name: "Draft",
        for: "Draft",
    },
];

export const DataNews = [
    {
        id: 1,
        type: "Default",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        for: "News",
    },
    {
        id: 2,
        type: "Default",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 hover:bg-gray-100",
        for: "News",
    },
    {
        id: 3,
        type: "The Pulse",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        for: "News",
    },
    {
        id: 4,
        type: "The Pulse",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 hover:bg-gray-100",
        for: "News",
    },
    {
        id: 5,
        type: "Default",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        for: "News",
    },
    {
        id: 6,
        type: "Default",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 hover:bg-gray-100",
        for: "News",
    },
    {
        id: 7,
        type: "The Pulse",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        for: "News",
    },
    {
        id: 8,
        type: "Default",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 hover:bg-gray-100",
        for: "News",
    },
    {
        id: 9,
        type: "The Pulse",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        for: "News",
    },
    {
        id: 10,
        type: "Default",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 hover:bg-gray-100",
        for: "News",
    },
    {
        id: 11,
        type: "The Pulse",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        for: "Draft",
    },
    {
        id: 12,
        type: "The Pulse",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 hover:bg-gray-100",
        for: "Draft",
    },
    {
        id: 13,
        type: "The Pulse",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        for: "Draft",
    },
    {
        id: 14,
        type: "The Pulse",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 hover:bg-gray-100",
        for: "Draft",
    },
    {
        id: 15,
        type: "The Pulse",
        title: "Waspada Fintech Ilegal, Kenali Ciri-cirinya",
        datePublish: "20 May 2023",
        color: "border-b border-gray-200 bg-gray-100 hover:bg-gray-50",
        for: "Draft",
    },
];

